version: '3'

services:
    postgres:
        image: 'postgres:14-alpine'
        container_name: 'postgres_notes_app'
        environment:
            - 'POSTGRES_USER=postgres'
            - 'POSTGRES_HOST_AUTH_METHOD=trust'
            - 'POSTGRES_DB=notes'

    app:
        build: ./
        container_name: 'NotesApp'
        ports:
            - "8080:8080"
