create TABLE note (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   creation_date TIMESTAMP with time zone,
   is_deleted BOOLEAN,
   user_id BIGINT,
   CONSTRAINT pk_note PRIMARY KEY (id)
);

create TABLE role (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_role PRIMARY KEY (id)
);

create TABLE "user" (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   registration_date TIMESTAMP with time zone,
   CONSTRAINT pk_user PRIMARY KEY (id)
);

create TABLE user_role (
   role_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

alter table "user" add CONSTRAINT uc_user_email UNIQUE (email);

alter table note add CONSTRAINT FK_NOTE_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

alter table user_role add CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);

alter table user_role add CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);

insert into role (name) values ('ROLE_ADMIN'), ('ROLE_USER');